CREATE DATABASE IF NOT EXISTS GestionProjetsEntreprise
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE GestionProjetsEntreprise;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS AFFECTATION;
DROP TABLE IF EXISTS REGLEMENT;
DROP TABLE IF EXISTS TACHE;
DROP TABLE IF EXISTS PROJET;
DROP TABLE IF EXISTS PERSONNEL;
DROP TABLE IF EXISTS SERVICE;
DROP TABLE IF EXISTS CHEF_PROJET;
DROP TABLE IF EXISTS CHEF_SERVICE;
DROP TABLE IF EXISTS TYPEPROJET;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS UTILISATEUR;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CLIENT (
  IdClient INT AUTO_INCREMENT PRIMARY KEY,
  NomClient VARCHAR(255) NOT NULL,
  AdresseClient VARCHAR(255) NULL,
  EmailClient VARCHAR(255) NULL,
  TelClient VARCHAR(50) NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE TYPEPROJET (
  IdTypeProjet INT AUTO_INCREMENT PRIMARY KEY,
  LibelleTypeProjet VARCHAR(255) NOT NULL,
  NomTypeProjet VARCHAR(255) NULL,
  ForfaitCoutTypeProjet DECIMAL(15,2) DEFAULT 0,
  DescriptionTypeProjet TEXT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE CHEF_PROJET (
  IdChefProjet INT AUTO_INCREMENT PRIMARY KEY,
  NomChefProjet VARCHAR(255) NOT NULL,
  PrenomChefProjet VARCHAR(255) NOT NULL,
  EmailChefProjet VARCHAR(255) NULL,
  TelChefProjet VARCHAR(50) NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE CHEF_SERVICE (
  IdChefService INT AUTO_INCREMENT PRIMARY KEY,
  NomChefService VARCHAR(255) NOT NULL,
  PrenomChefService VARCHAR(255) NOT NULL,
  EmailChefService VARCHAR(255) NULL,
  TelChefService VARCHAR(50) NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE SERVICE (
  CodeService VARCHAR(50) PRIMARY KEY,
  LibelleService VARCHAR(255) NOT NULL,
  TypeService VARCHAR(255) NULL,
  DescriptionService TEXT NULL,
  IdChefService INT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_SERVICE_CHEF_SERVICE FOREIGN KEY (IdChefService)
    REFERENCES CHEF_SERVICE(IdChefService)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE PERSONNEL (
  MatriculePersonnel VARCHAR(50) PRIMARY KEY,
  NomPersonnel VARCHAR(255) NOT NULL,
  PrenomPersonnel VARCHAR(255) NOT NULL,
  EmailPersonnel VARCHAR(255) NULL,
  TelPersonnel VARCHAR(50) NULL,
  DateEmbauche DATE NULL,
  CodeService VARCHAR(50) NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_PERSONNEL_SERVICE FOREIGN KEY (CodeService)
    REFERENCES SERVICE(CodeService)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE PROJET (
  IdProjet INT AUTO_INCREMENT PRIMARY KEY,
  TitreProjet VARCHAR(255) NOT NULL,
  DescriptionProjet TEXT NULL,
  CoutProjet DECIMAL(15,2) DEFAULT 0,
  DateDebutProjet DATE NULL,
  DateFinProjet DATE NULL,
  EtatProjet TINYINT NOT NULL DEFAULT 1,
  IdClient INT NOT NULL,
  IdTypeProjet INT NOT NULL,
  IdChefProjet INT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_PROJET_CLIENT FOREIGN KEY (IdClient)
    REFERENCES CLIENT(IdClient)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_PROJET_TYPE FOREIGN KEY (IdTypeProjet)
    REFERENCES TYPEPROJET(IdTypeProjet)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_PROJET_CHEF FOREIGN KEY (IdChefProjet)
    REFERENCES CHEF_PROJET(IdChefProjet)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT CK_PROJET_ETAT CHECK (EtatProjet IN (1, 2, 3))
) ENGINE=InnoDB;

CREATE TABLE TACHE (
  IdTache INT AUTO_INCREMENT PRIMARY KEY,
  LibelleTache VARCHAR(255) NOT NULL,
  DescriptionTache TEXT NULL,
  DateEnregTache DATE NULL,
  DateDebutTache DATE NULL,
  DateFinTache DATE NULL,
  EtatTache TINYINT NOT NULL DEFAULT 1,
  IdProjet INT NOT NULL,
  CodeService VARCHAR(50) NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_TACHE_PROJET FOREIGN KEY (IdProjet)
    REFERENCES PROJET(IdProjet)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_TACHE_SERVICE FOREIGN KEY (CodeService)
    REFERENCES SERVICE(CodeService)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT CK_TACHE_ETAT CHECK (EtatTache IN (1, 2, 3, 4))
) ENGINE=InnoDB;

CREATE TABLE REGLEMENT (
  IdReglement INT AUTO_INCREMENT PRIMARY KEY,
  IdProjet INT NOT NULL,
  DateReglement DATE NOT NULL,
  HeureReglement TIME NULL,
  MontantReglement DECIMAL(15,2) NOT NULL DEFAULT 0,
  ModePaiementReglement VARCHAR(80) NULL,
  ReferenceReglement VARCHAR(255) NULL,
  CommentaireReglement TEXT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_REGLEMENT_PROJET FOREIGN KEY (IdProjet)
    REFERENCES PROJET(IdProjet)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE AFFECTATION (
  IdAffectation INT AUTO_INCREMENT PRIMARY KEY,
  IdTache INT NOT NULL,
  MatriculePersonnel VARCHAR(50) NOT NULL,
  DateAffectation DATE NULL,
  HeureAffectation TIME NULL,
  FonctionAffectation VARCHAR(255) NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UK_AFFECTATION_TACHE_PERSONNEL (IdTache, MatriculePersonnel),
  CONSTRAINT FK_AFFECTATION_TACHE FOREIGN KEY (IdTache)
    REFERENCES TACHE(IdTache)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_AFFECTATION_PERSONNEL FOREIGN KEY (MatriculePersonnel)
    REFERENCES PERSONNEL(MatriculePersonnel)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE UTILISATEUR (
  IdUtilisateur INT AUTO_INCREMENT PRIMARY KEY,
  NomUtilisateur VARCHAR(255) NOT NULL UNIQUE,
  EmailUtilisateur VARCHAR(255) NULL UNIQUE,
  MotDePasse VARCHAR(255) NOT NULL,
  Role VARCHAR(50) NOT NULL DEFAULT 'personnel',
  DerniereConnexion DATETIME NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT CK_UTILISATEUR_ROLE CHECK (Role IN ('admin', 'chef_projet', 'chef_service', 'personnel'))
) ENGINE=InnoDB;
